### ISSUE TITLE
Install woes

### ISSUE THREAD

**Issue by wbw60** [milhead2/python-j1939#6]
Miller and all,
  I'm having an issue running setup.py on a Raspberry Pi running the raspian version of debian 9.9 ("stretch" is the version name) . I installed python-can in my local directory and then ran "sudo python3 setup.py develop". I installed python-j1939-master in my local directory and ran "python3 setup.py test" and got the following output:
+++++++++++++++++++++++++++++++
/usr/lib/python3/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.1.0-alpha.3' to '0.1.0a3'
  normalized_version,
running test
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py3.5.egg

Using /home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/nose-1.3.7-py3.5.egg
Searching for mock
Best match: mock 3.0.5
Processing mock-3.0.5-py3.5.egg

Using /home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/mock-3.0.5-py3.5.egg
running egg_info
writing python_j1939.egg-info/PKG-INFO
writing dependency_links to python_j1939.egg-info/dependency_links.txt
writing top-level names to python_j1939.egg-info/top_level.txt
writing requirements to python_j1939.egg-info/requires.txt
reading manifest file 'python_j1939.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst' under directory 'doc'
writing manifest file 'python_j1939.egg-info/SOURCES.txt'
running build_ext
Failure: SyntaxError (invalid syntax (__init__.py, line 15)) ... ERROR

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (__init__.py, line 15))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/nose-1.3.7-py3.5.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/nose-1.3.7-py3.5.egg/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/nose-1.3.7-py3.5.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/pi/CANplay/wbwPlay/python-j1939-master/.eggs/nose-1.3.7-py3.5.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/CANplay/wbwPlay/python-j1939-master/j1939/__init__.py", line 25, in <module>
    from can import CanError
  File "/home/pi/CANplay/wbwPlay/python-can-develop/can/__init__.py", line 15
    rc: Dict[str, Any] = dict()
      ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 1 test in 0.023s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
+++++++++++++++++++
Is there an environment variable I need to set? Anything obvious that I've done here or failed to do? Thanks in advance for your help. 

Regards,
 Bill Walden

**Comment by wbw60** [comment]
I got it working. First, after reading Miller's latest update, I downloaded the source code for version 3.3.2 of python-can found at https://github.com/hardbyte/python-can/releases . Then I went into the downloaded python-can directory and typed:
-------------------
python3 setup.py build
sudo python3 setup.py install
-------------------
And then repeated those commands in the python-j1939-master directories. After that I ran the j1939_logger.py file on can0 and was able to see the J1939 messages going by. The upshot is that I didn't know what commands to give to setup.py to build and install the packages (perhaps this should go into the README file?). Closing.
